### ISSUE TITLE
Solicitações de funções

### ISSUE THREAD

**Issue by animetrom** [ItsMadruga/MdgWa#1]
Primeiramente, gostaria de parabenizar pelo excelente modulo, pois é simplesmente magnifico!
Queria dar umas dicas de funções novas, se puder adicionar.
1- Adicionar opção para esconder conversas arquivadas completamente.
2- Ocultar microfone azul
3- Privacidade de chamadas, onde posso selecionar se quero todos, meus contatos, contatos específicos ou ninguém.
4- Enviar imagens em resolução total, enviar vídeos com mais de 16mb, enviar áudios com mais de 16mb.
5- Fixar mais de 3 chats
6- Aumentar o limite de encaminhamento (com um aviso de uso por conta e risco com chance de ban)
7- Mensagens anti-edição, quando editada, mostrará a mensagem original junto com a editada.

Essas são as funções que acharia legal colocar, se possível. Agradeço mais uma vez pelo projeto e parabéns de verdade!

**Comment by ItsMadruga** [comment]
Opa, obrigado, vou ver oq posso fazer, trarei uma atualização em breve.

:)
