### ISSUE TITLE
Notification Counter

### ISSUE THREAD

**Issue by Sven-Pixel** [ItsMadruga/MdgWa#23]
Notification Counter shows new message in a group on the Icon for Chats.
![Screenshot_20240323-110244~2](https://github.com/ItsMadruga/MdgWa/assets/107144691/38b58f6c-e5c3-4f8a-943a-90702861b9c1)
![Screenshot_20240323-110251~2](https://github.com/ItsMadruga/MdgWa/assets/107144691/61c656a5-9783-4ed7-8091-9dc236c1a4a5)

**Comment by Sven-Pixel** [comment]
Solved.

**Comment by HikaruIchijyo** [comment]
> Solved.

Already solved
