### ISSUE TITLE
Arquivo nulo no StatusDownload

### ISSUE THREAD

**Issue by Dev4Mod** [ItsMadruga/MdgWa#26]
Olhando para a linha de código https://github.com/ItsMadruga/MdgWa/blob/989c66242c71abd8395818a8277f783570931e85/app/src/main/java/its/madruga/wpp/xposed/plugins/functions/XStatusDownload.java#L40 percebi que não é um local seguro para obter o arquivo para download.
Seria melhor o "StatusPlaybackPage/onCreate" aqui o arquivo vai existe assim que o whatsapp baixar o arquivo do servidores.
Também sugiro separar o gancho para incluir o botão de download, seria interessante colocar o File em um campo estático.

Caso queira, posso lançar um commit com as mudanças necessária.

**Comment by ItsMadruga** [comment]
WhatsApp downloads the status while it is played, so it wouldn't make any difference

**Comment by ItsMadruga** [comment]
mas se quiser lance um commit para analisarmos
