### ISSUE TITLE
issue when using Whatsapp WEB

### ISSUE THREAD

**Issue by SychoAN** [ItsMadruga/MdgWa#27]
I tried the beta versions..it's working great and no with no issues
but only when I open whatsapp Web on my computer...I get the new messages on computer only!
no updates on phone till I disable the module
--
it will sync for new messages with whatsapp web only when I disable the module

so just open whatsapp web and make a small chat with a friend
and please check if this issue happens with me only or not

**Comment by ItsMadruga** [comment]
some functions are really causing delay, but it is not something we can fix, as it is the whatsapp server
