### ISSUE TITLE
Problem trying to install the module.

### ISSUE THREAD

**Issue by yuzamei2854** [ItsMadruga/MdgWa#33]
Hi, I'm having problems installing the module, after trying to install it from the file manager I get an error saying: `There was a problem analysing the package`, as you can see in the image below:

![Screenshot_20240401-000222_Package installer_1](https://github.com/ItsMadruga/MdgWa/assets/141790911/0ae8ac5d-dbe9-4a51-b389-760e44e52075)

I tried using [SAI](https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=pt_BR&gl=US) to get information about the problem, but it didn't work, it just returns to the Android's package installer.

I don't know what the problem could be, I'm using Android 9, I have free space and I tried downloading again to check if the app was corrupted, but it's still the same.

The module icon is empty as you can see in the image below:

![Screenshot_20240401-000308_Material Files_1](https://github.com/ItsMadruga/MdgWa/assets/141790911/6023753f-e501-4904-899e-fa554fe05d02)

**Comment by Dev4Mod** [comment]
the developer set the minimum supported version starting from Android 10
https://github.com/ItsMadruga/MdgWa/blob/2005cbe4f669b0014ac7ea072d60abf145a6d2eb/app/build.gradle.kts#L12

**Comment by Dev4Mod** [comment]
This module using lsposed sharedprefs which was introduced from Android 9 so I believe it is supported if Dev puts Android as minimum 9
https://github.com/ItsMadruga/MdgWa/blob/2005cbe4f669b0014ac7ea072d60abf145a6d2eb/app/src/main/AndroidManifest.xml#L34

[Lsposed Doc](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences)

**Comment by yuzamei2854** [comment]
> the developer set the minimum supported version starting from Android 10
> 
> https://github.com/ItsMadruga/MdgWa/blob/2005cbe4f669b0014ac7ea072d60abf145a6d2eb/app/build.gradle.kts#L12

Oh, thanks, the developer should have put that on the project's home page as a restriction/requirement.

**Comment by Darker935** [comment]
Done, thanks @Dev4Mod
