### ISSUE TITLE
How to remove this icon

### ISSUE THREAD

**Issue by hphp22f** [ItsMadruga/MdgWa#34]
![Screenshot_2024-04-01-14-45-54-770-edit_com whatsapp](https://github.com/ItsMadruga/MdgWa/assets/151181919/2947afb3-d58f-4387-8164-f6f62e53f076)

**Comment by hphp22f** [comment]
It says how to hide it

**Comment by ItsMadruga** [comment]
it is not planned

**Comment by hphp22f** [comment]
> it is not planned

So add something to remove it in next update, please
