### ISSUE TITLE
Create new branch for early support to dexkit

### ISSUE THREAD

**Issue by Dev4Mod** [ItsMadruga/MdgWa#37]
Create a branch with support for newer versions of WhatsApp using dynamic search for classes and methods, if you are interested, check at: https://github.com/Dev4Mod/MdgWa/tree/dexkit

**Comment by Dev4Mod** [comment]
I didn't receive feedback from Dev regarding this, so I'll only support my

**Comment by HikaruIchijyo** [comment]
> I didn't receive feedback from Dev regarding this, so I'll only support my fork

It will be available soon they both r busy currently
