### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by RevealedSoulEven** [ItsMadruga/MdgWa#4]
Why isn't the project open source? It should help to create pr

**Comment by Darker935** [comment]
We are organizing everything to make it public

**Comment by HikaruIchijyo** [comment]
Yay

**Comment by HikaruIchijyo** [comment]
> Why isn't the project open source? It should help to create pr

Released

**Comment by RevealedSoulEven** [comment]
Get ready for contributions dude😻
